version: "3.3"

services:
  image-app:
    container_name: image-app
    restart: always
    build: ./
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb://mongo:27017/image-app-db
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
